### ISSUE TITLE
Un-installable from PyPI

### ISSUE THREAD

**Issue by kylef** [jhermann/pygments-markdown-lexer#2]
Not sure why, since the version is listed on https://pypi.python.org/pypi/pygments-markdown-lexer, but following the instructions to install the lexer via pip from the README results in aa failure because it's not found.

``` bash
$  pip install pygments-markdown-lexer
Downloading/unpacking pygments-markdown-lexer
  Could not find any downloads that satisfy the requirement pygments-markdown-lexer
Cleaning up...
No distributions at all found for pygments-markdown-lexer
Storing debug log for failure in /Users/kyle/.pip/pip.log

$ cat /Users/kyle/.pip/pip.log
------------------------------------------------------------
/Users/kyle/Projects/kylef/bluepaste/venv/bin/pip run on Mon Jul  6 01:09:01 2015
Downloading/unpacking pygments-markdown-lexer
  Getting page https://pypi.python.org/simple/pygments-markdown-lexer/
  URLs to search for versions for pygments-markdown-lexer:
  * https://pypi.python.org/simple/pygments-markdown-lexer/
  Analyzing links from page https://pypi.python.org/simple/pygments-markdown-lexer/
  Could not find any downloads that satisfy the requirement pygments-markdown-lexer
Cleaning up...
  Removing temporary dir /Users/kyle/Projects/kylef/bluepaste/venv/build...
No distributions at all found for pygments-markdown-lexer
Exception information:
Traceback (most recent call last):
  File "/Users/kyle/Projects/kylef/bluepaste/venv/lib/python2.7/site-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/Users/kyle/Projects/kylef/bluepaste/venv/lib/python2.7/site-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/Users/kyle/Projects/kylef/bluepaste/venv/lib/python2.7/site-packages/pip/req.py", line 1177, in prepare_files
    url = finder.find_requirement(req_to_install, upgrade=self.upgrade)
  File "/Users/kyle/Projects/kylef/bluepaste/venv/lib/python2.7/site-packages/pip/index.py", line 277, in find_requirement
    raise DistributionNotFound('No distributions at all found for %s' % req)
DistributionNotFound: No distributions at all found for pygments-markdown-lexer
```

**Comment by jhermann** [comment]
That's because there is no release yet; a .dev snapshot is now on pypi.
